name: Build

on:
  workflow_dispatch:
    inputs:
      release_tag:
        required: true
        description: 'Release tag something like v5.23.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'

    - name: Patch Go use 600296
      if: steps.cache-libv2ray-restore.outputs.cache-hit != 'true'
      #https://go-review.googlesource.com/c/go/+/600296
      run: |
       cd "$(go env GOROOT)"
       curl "https://go-review.googlesource.com/changes/go~600296/revisions/5/patch" | base64 -d | patch --verbose -p 1
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:~/go/bin
  
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.2
      with:
        cmdline-tools-version: 10406996
        
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.5.0
      with:
        ndk-version: 'r27b'
        link-to-sdk: true
    
    - name: Build
      run: |
         mkdir -p assets data
         bash gen_assets.sh download
         cp -v data/*.dat assets/
         gomobile init
         go mod tidy
         gomobile bind -v -androidapi 21 -ldflags='-s -w' ./
    - name: Upload AndroidLibV2rayLite to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./libv2ray*r
        tag: ${{ github.event.inputs.release_tag }}
        file_glob: true
